apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-consumer
  namespace: portfolio
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics
      app.kubernetes.io/component: consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics
        app.kubernetes.io/component: consumer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: consumer
          image: ghcr.io/szymonborowski/microservices-analytics:v0.0.1
          args: ["php", "artisan", "rabbitmq:consume-views"]
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
